services:
#  scrum-front-end:
#    build: ./front-end
#    container_name: scrum-front-end
#    ports:
#      - '80:80'
#    expose:
#      - '80'
  scrum-discovery-service:
    build: ./discovery-service
    container_name: scrum-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  scrum-config-service:
    build: ./config-service
    container_name: scrum-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://scrum-discovery-service:8761/eureka #la variable d'envirenement
    depends_on:
      scrum-discovery-service:
        condition: service_healthy
  scrum-gateway-service:
    build: ./gateway-service
    container_name: scrum-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://scrum-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://scrum-config-service:9999
    depends_on:
      scrum-config-service:
        condition: service_healthy
  scrum-project-service:
    build: ./project-service
    container_name: scrum-project-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://scrum-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://scrum-config-service:9999
    depends_on:
      scrum-gateway-service:
        condition: service_healthy
  scrum-sprint-service:
    build: ./sprint-service
    container_name: scrum-sprint-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://scrum-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://scrum-config-service:9999
    depends_on:
      scrum-project-service:
        condition: service_healthy