spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*' # * pour veut dir que autorisee tout les sites
            allowed-headers: '*'
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE